SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `flights`;
CREATE TABLE `flights`
(
    `id`            INT             NOT NULL AUTO_INCREMENT,
    `flight_number` varchar(6)      NOT NULL,
    `origin`        CHAR(3)     NOT NULL,
    `destination`   CHAR(3)     DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `flight_number_unique` (`flight_number`),
    CONSTRAINT `fk_origin` FOREIGN KEY (`origin`)
        REFERENCES `airports` (`IATA`),
    CONSTRAINT `fk_destination` FOREIGN KEY (`destination`)
        REFERENCES `airports` (`IATA`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

INSERT INTO `flights` (`flight_number`, `origin`, `destination`)
VALUES
    ('BA101', 'LHR', 'JFK'),
    ('LH102', 'FRA', 'ORD'),
    ('AF203', 'CDG', 'LAX'),
    ('EK104', 'DXB', 'SIN'),
    ('SQ105', 'SIN', 'SYD'),
    ('AA206', 'DFW', 'LAX'),
    ('QF207', 'SYD', 'LHR'),
    ('CX208', 'HKG', 'CDG'),
    ('DL209', 'ATL', 'JFK'),
    ('UA210', 'DEN', 'ORD'),
    ('NZ211', 'AKL', 'BNE'),
    ('LS212', 'LBA', 'MAN'),
    ('OS213', 'VIE', 'ZRH'),
    ('TK214', 'IST', 'TLV'),
    ('BA301', 'LHR', 'SFO'),
    ('LH302', 'FRA', 'HKG'),
    ('AF303', 'CDG', 'SYD'),
    ('EK304', 'DXB', 'JFK'),
    ('SQ305', 'SIN', 'ORD'),
    ('AA406', 'DFW', 'MIA'),
    ('QF407', 'SYD', 'BNE'),
    ('CX408', 'HKG', 'NRT'),
    ('DL409', 'ATL', 'MIA'),
    ('UA410', 'DEN', 'JFK'),
    ('NZ411', 'AKL', 'MEL'),
    ('LS412', 'LBA', 'BHX'),
    ('OS413', 'VIE', 'AMS'),
    ('TK414', 'IST', 'FCO'),
    ('BA505', 'LHR', 'MEX'),
    ('LH506', 'FRA', 'VIE'),
    ('AF507', 'CDG', 'MAD'),
    ('EK508', 'DXB', 'LON'),
    ('SQ509', 'SIN', 'SFO'),
    ('AA610', 'DFW', 'LHR'),
    ('QF611', 'SYD', 'MEL'),
    ('CX612', 'HKG', 'SYD'),
    ('DL613', 'ATL', 'LAX'),
    ('UA614', 'DEN', 'SFO'),
    ('NZ615', 'AKL', 'CHC'),
    ('LS616', 'LBA', 'GLA'),
    ('OS617', 'VIE', 'LHR'),
    ('TK618', 'IST', 'JFK'),
    ('BA701', 'LHR', 'MAD'),
    ('LH702', 'FRA', 'LAX'),
    ('AF703', 'CDG', 'LHR'),
    ('EK704', 'DXB', 'IST'),
    ('SQ705', 'SIN', 'HKG'),
    ('AA806', 'DFW', 'SYD'),
    ('QF807', 'SYD', 'AKL'),
    ('CX808', 'HKG', 'LAX'),
    ('DL809', 'ATL', 'SFO'),
    ('UA810', 'DEN', 'SYD'),
    ('NZ811', 'AKL', 'BNE'),
    ('LS812', 'LBA', 'LCY'),
    ('OS813', 'VIE', 'MUC'),
    ('TK814', 'IST', 'BER'),
    ('BA901', 'LHR', 'JFK'),
    ('LH902', 'FRA', 'SYD'),
    ('AF903', 'CDG', 'SFO'),
    ('EK904', 'DXB', 'LAX'),
    ('SQ905', 'SIN', 'ORD'),
    ('AA1001', 'DFW', 'LHR'),
    ('QF1002', 'SYD', 'BNE'),
    ('CX1003', 'HKG', 'NRT'),
    ('DL1004', 'ATL', 'LAX'),
    ('UA1005', 'DEN', 'SFO'),
    ('NZ1006', 'AKL', 'SYD'),
    ('LS1007', 'LBA', 'EGL'),
    ('OS1008', 'VIE', 'LHR'),
    ('TK1009', 'IST', 'TLV'),
    ('BA1101', 'LHR', 'SFO'),
    ('LH1102', 'FRA', 'LAX'),
    ('AF1103', 'CDG', 'LHR'),
    ('EK1104', 'DXB', 'SIN'),
    ('SQ1105', 'SIN', 'SYD'),
    ('AA1206', 'DFW', 'ORD'),
    ('QF1207', 'SYD', 'SYD'),
    ('CX1208', 'HKG', 'SFO'),
    ('DL1209', 'ATL', 'ORD'),
    ('UA1210', 'DEN', 'JFK'),
    ('NZ1211', 'AKL', 'WLG'),
    ('LS1212', 'LBA', 'STN'),
    ('OS1213', 'VIE', 'AMS'),
    ('TK1214', 'IST', 'CDG'),
    ('BA1301', 'LHR', 'FRA'),
    ('LH1302', 'FRA', 'MIA'),
    ('AF1303', 'CDG', 'SYD'),
    ('EK1304', 'DXB', 'HKG'),
    ('SQ1305', 'SIN', 'AKL'),
    ('AA1406', 'DFW', 'SYD'),
    ('QF1407', 'SYD', 'MEL'),
    ('CX1408', 'HKG', 'ORD'),
    ('DL1409', 'ATL', 'LAX'),
    ('UA1410', 'DEN', 'MIA'),
    ('NZ1411', 'AKL', 'AKL'),
    ('LS1412', 'LBA', 'LHR'),
    ('OS1413', 'VIE', 'ZRH'),
    ('TK1414', 'IST', 'LAX');
